# docker-compose.yml

services:
  # Layanan Aplikasi Laravel dengan FrankenPHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"       # Port HTTP
      - "443:443"     # Port HTTPS
      - "443:443/udp" # Port untuk HTTP/3
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      # Arahkan koneksi ke layanan database 'db'
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE:-sitikdb}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      # Beritahu Laravel untuk menemukan Vite di layanan 'vite'
      VITE_SERVER_HOST: vite
      # URL Server untuk HTTPS otomatis dari Caddy/FrankenPHP
      SERVER_NAME: "localhost"

  # --- LAYANAN BARU UNTUK VITE DEV SERVER ---
  vite:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      # Buka port Vite agar bisa diakses dari browser
      - "5173:5173"
    # Perintah untuk menginstal dependensi dan menjalankan server dev
    command: sh -c "npm install && npm run dev -- --host"

  # Layanan Database PostgreSQL
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-sitikdb}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
